/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import TSPrincipal.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;


public class VentanaGestionarTareas extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    public String Nombre(){
        return("¡"+TSPrincipal.Sistema.getUsuarioActual().getNombre()+"!");
    }
    

    public String MostrarTareas(){
    Usuario UsuarioActual = TSPrincipal.Sistema.getUsuarioActual();
    return UsuarioActual.obtenerTareas();
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaGestionarTareas.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaGestionarTareas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorBG = new javax.swing.JPanel();
        Panel2Inicio = new javax.swing.JPanel();
        PanelLindo = new javax.swing.JPanel();
        IconoTimeSaver = new javax.swing.JLabel();
        TimeSaver = new javax.swing.JLabel();
        HolaUser = new javax.swing.JLabel();
        EligeOpcion = new javax.swing.JLabel();
        AgregarTarea = new javax.swing.JPanel();
        AgregarTXT = new javax.swing.JLabel();
        EditarTarea = new javax.swing.JPanel();
        EditTXT = new javax.swing.JLabel();
        CompletarTarea = new javax.swing.JPanel();
        CompleteTXT = new javax.swing.JLabel();
        EliminarTarea = new javax.swing.JPanel();
        EliminarTXT = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TareasTXT = new javax.swing.JTextArea();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();
        VolverInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(73, 38, 97));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2Inicio.setBackground(new java.awt.Color(147, 100, 160));

        PanelLindo.setBackground(new java.awt.Color(203, 170, 224));

        IconoTimeSaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono.png"))); // NOI18N
        IconoTimeSaver.setToolTipText("");

        TimeSaver.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeSaver.setForeground(new java.awt.Color(0, 0, 0));
        TimeSaver.setText("TimeSaver");

        HolaUser.setBackground(new java.awt.Color(0, 0, 0));
        HolaUser.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        HolaUser.setForeground(new java.awt.Color(0, 0, 0));
        HolaUser.setText(Nombre());

        EligeOpcion.setBackground(new java.awt.Color(0, 0, 0));
        EligeOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EligeOpcion.setForeground(new java.awt.Color(0, 0, 0));
        EligeOpcion.setText("¿Que deseas hacer con tus tareas?");

        AgregarTarea.setBackground(new java.awt.Color(147, 100, 160));

        AgregarTXT.setBackground(new java.awt.Color(0, 0, 0));
        AgregarTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        AgregarTXT.setForeground(new java.awt.Color(0, 0, 0));
        AgregarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarTXT.setText("Agregar Tarea");
        AgregarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarTareaLayout = new javax.swing.GroupLayout(AgregarTarea);
        AgregarTarea.setLayout(AgregarTareaLayout);
        AgregarTareaLayout.setHorizontalGroup(
            AgregarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        AgregarTareaLayout.setVerticalGroup(
            AgregarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        EditarTarea.setBackground(new java.awt.Color(147, 100, 160));

        EditTXT.setBackground(new java.awt.Color(0, 0, 0));
        EditTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        EditTXT.setForeground(new java.awt.Color(0, 0, 0));
        EditTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditTXT.setText("Editar Tarea");
        EditTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EditarTareaLayout = new javax.swing.GroupLayout(EditarTarea);
        EditarTarea.setLayout(EditarTareaLayout);
        EditarTareaLayout.setHorizontalGroup(
            EditarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        EditarTareaLayout.setVerticalGroup(
            EditarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        CompletarTarea.setBackground(new java.awt.Color(147, 100, 160));

        CompleteTXT.setBackground(new java.awt.Color(0, 0, 0));
        CompleteTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        CompleteTXT.setForeground(new java.awt.Color(0, 0, 0));
        CompleteTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompleteTXT.setText("Completar Tarea");
        CompleteTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompleteTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompleteTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CompleteTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CompleteTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CompletarTareaLayout = new javax.swing.GroupLayout(CompletarTarea);
        CompletarTarea.setLayout(CompletarTareaLayout);
        CompletarTareaLayout.setHorizontalGroup(
            CompletarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompleteTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        CompletarTareaLayout.setVerticalGroup(
            CompletarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompleteTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        EliminarTarea.setBackground(new java.awt.Color(147, 100, 160));

        EliminarTXT.setBackground(new java.awt.Color(0, 0, 0));
        EliminarTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        EliminarTXT.setForeground(new java.awt.Color(0, 0, 0));
        EliminarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarTXT.setText("Eliminar Tarea");
        EliminarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EliminarTareaLayout = new javax.swing.GroupLayout(EliminarTarea);
        EliminarTarea.setLayout(EliminarTareaLayout);
        EliminarTareaLayout.setHorizontalGroup(
            EliminarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EliminarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        EliminarTareaLayout.setVerticalGroup(
            EliminarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EliminarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelLindoLayout = new javax.swing.GroupLayout(PanelLindo);
        PanelLindo.setLayout(PanelLindoLayout);
        PanelLindoLayout.setHorizontalGroup(
            PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLindoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(IconoTimeSaver)
                        .addGap(18, 18, 18)
                        .addComponent(TimeSaver))
                    .addComponent(HolaUser)
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EligeOpcion)
                            .addGroup(PanelLindoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CompletarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelLindoLayout.setVerticalGroup(
            PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLindoLayout.createSequentialGroup()
                .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(IconoTimeSaver))
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TimeSaver)))
                .addGap(18, 18, 18)
                .addComponent(HolaUser)
                .addGap(18, 18, 18)
                .addComponent(EligeOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(EditarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompletarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PanelMenu.setBackground(new java.awt.Color(203, 170, 224));

        TareasTXT.setBackground(new java.awt.Color(203, 170, 224));
        TareasTXT.setColumns(20);
        TareasTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TareasTXT.setForeground(new java.awt.Color(0, 0, 0));
        TareasTXT.setRows(5);
        TareasTXT.setText(MostrarTareas());
        TareasTXT.setBorder(null);
        jScrollPane1.setViewportView(TareasTXT);

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout Panel2InicioLayout = new javax.swing.GroupLayout(Panel2Inicio);
        Panel2Inicio.setLayout(Panel2InicioLayout);
        Panel2InicioLayout.setHorizontalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(PanelLindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Panel2InicioLayout.setVerticalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ColorBG.add(Panel2Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 410));

        BarraSuperior.setBackground(new java.awt.Color(73, 38, 97));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(73, 38, 97));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 750, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        VolverInicio.setBackground(new java.awt.Color(255, 255, 255));
        VolverInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        VolverInicio.setText("<- Volver al menu principal (> w <)");
        VolverInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverInicioMouseExited(evt);
            }
        });
        ColorBG.add(VolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    System.exit(0);
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void VolverInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseEntered
    VolverInicio.setBackground(new Color(239, 98, 215));
    VolverInicio.setForeground(new Color(239, 98, 215));
        
    }//GEN-LAST:event_VolverInicioMouseEntered

    private void VolverInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseExited
    VolverInicio.setBackground(Color.white);
    VolverInicio.setForeground(Color.white);
    }//GEN-LAST:event_VolverInicioMouseExited

    private void VolverInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseClicked
    new Visual.VentanaMenuPrincipal().show(true);
    this.dispose();
    }//GEN-LAST:event_VolverInicioMouseClicked

    private void AgregarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseEntered
    AgregarTarea.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_AgregarTXTMouseEntered

    private void EditTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTXTMouseEntered
    EditarTarea.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_EditTXTMouseEntered

    private void CompleteTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompleteTXTMouseEntered
    CompletarTarea.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_CompleteTXTMouseEntered

    private void EliminarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTXTMouseEntered
    EliminarTarea.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_EliminarTXTMouseEntered

    private void AgregarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseExited
    AgregarTarea.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_AgregarTXTMouseExited

    private void EditTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTXTMouseExited
    EditarTarea.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_EditTXTMouseExited

    private void CompleteTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompleteTXTMouseExited
    CompletarTarea.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_CompleteTXTMouseExited

    private void EliminarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTXTMouseExited
    EliminarTarea.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_EliminarTXTMouseExited

    private void AgregarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseClicked
    new Visual.VentanaEmergente1().show(true);
    
    }//GEN-LAST:event_AgregarTXTMouseClicked

    private void EditTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTXTMouseClicked
    new Visual.VentanaEmergente2().show(true);
    }//GEN-LAST:event_EditTXTMouseClicked

    private void CompleteTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompleteTXTMouseClicked
    new Visual.VentanaEmergente3().show(true);
    }//GEN-LAST:event_CompleteTXTMouseClicked

    private void EliminarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTXTMouseClicked
    new Visual.VentanaEmergente4().show(true);
    }//GEN-LAST:event_EliminarTXTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarTXT;
    private javax.swing.JPanel AgregarTarea;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JPanel CompletarTarea;
    private javax.swing.JLabel CompleteTXT;
    private javax.swing.JLabel EditTXT;
    private javax.swing.JPanel EditarTarea;
    private javax.swing.JLabel EligeOpcion;
    private javax.swing.JLabel EliminarTXT;
    private javax.swing.JPanel EliminarTarea;
    private javax.swing.JLabel HolaUser;
    private javax.swing.JLabel IconoTimeSaver;
    private javax.swing.JPanel Panel2Inicio;
    private javax.swing.JPanel PanelLindo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JTextArea TareasTXT;
    private javax.swing.JLabel TimeSaver;
    private javax.swing.JLabel VolverInicio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
