/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import TSPrincipal.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;


public class VentanaInicioSesion extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaInicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        ColorBG = new javax.swing.JPanel();
        Panel2Inicio = new javax.swing.JPanel();
        TimeSaver = new javax.swing.JLabel();
        IconoTimeSaver = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        AnimeGirl = new javax.swing.JLabel();
        TedamoslaBienvenida = new javax.swing.JLabel();
        EligeOpcion = new javax.swing.JLabel();
        UsuarioTXT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UsuarioField = new javax.swing.JTextField();
        BotonEntrar = new javax.swing.JPanel();
        EntrarTXT = new javax.swing.JLabel();
        VolverInicio = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(73, 38, 97));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2Inicio.setBackground(new java.awt.Color(147, 100, 160));

        TimeSaver.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeSaver.setForeground(new java.awt.Color(255, 255, 255));
        TimeSaver.setText("TimeSaver");

        IconoTimeSaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono.png"))); // NOI18N
        IconoTimeSaver.setToolTipText("");

        PanelMenu.setBackground(new java.awt.Color(46, 46, 52));

        AnimeGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AnimeGirl.png"))); // NOI18N

        TedamoslaBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        TedamoslaBienvenida.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        TedamoslaBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        TedamoslaBienvenida.setText("¡Bienvenido!");

        EligeOpcion.setBackground(new java.awt.Color(255, 255, 255));
        EligeOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EligeOpcion.setForeground(new java.awt.Color(255, 255, 255));
        EligeOpcion.setText("Ingresa tu ID de usuario a continuación:");

        UsuarioTXT.setBackground(new java.awt.Color(255, 255, 255));
        UsuarioTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        UsuarioTXT.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTXT.setText("ID Usuario:");

        UsuarioField.setBackground(new java.awt.Color(46, 46, 52));
        UsuarioField.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioField.setText("Ingresa tu ID de usuario");
        UsuarioField.setBorder(null);
        UsuarioField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioFieldMousePressed(evt);
            }
        });
        UsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioFieldActionPerformed(evt);
            }
        });

        BotonEntrar.setBackground(new java.awt.Color(88, 101, 242));

        EntrarTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EntrarTXT.setForeground(new java.awt.Color(255, 255, 255));
        EntrarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EntrarTXT.setText("Entrar");
        EntrarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonEntrarLayout = new javax.swing.GroupLayout(BotonEntrar);
        BotonEntrar.setLayout(BotonEntrarLayout);
        BotonEntrarLayout.setHorizontalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EntrarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        BotonEntrarLayout.setVerticalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EntrarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(EligeOpcion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(TedamoslaBienvenida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(UsuarioField, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsuarioTXT))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AnimeGirl)
                        .addGap(40, 40, 40))))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TedamoslaBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EligeOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnimeGirl)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(UsuarioTXT)
                        .addGap(7, 7, 7)
                        .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        VolverInicio.setBackground(new java.awt.Color(255, 255, 255));
        VolverInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        VolverInicio.setText("<- Volver al inicio (> w <)");
        VolverInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel2InicioLayout = new javax.swing.GroupLayout(Panel2Inicio);
        Panel2Inicio.setLayout(Panel2InicioLayout);
        Panel2InicioLayout.setHorizontalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(IconoTimeSaver)
                        .addGap(18, 18, 18)
                        .addComponent(TimeSaver))
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VolverInicio)
                            .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        Panel2InicioLayout.setVerticalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoTimeSaver))
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TimeSaver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverInicio)
                .addGap(197, 197, 197))
        );

        ColorBG.add(Panel2Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 410));

        BarraSuperior.setBackground(new java.awt.Color(73, 38, 97));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(73, 38, 97));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 750, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    System.exit(0);
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void UsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioFieldActionPerformed

    private void UsuarioFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioFieldMousePressed
    UsuarioField.setText("");
    }//GEN-LAST:event_UsuarioFieldMousePressed

    private void VolverInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseEntered
    VolverInicio.setBackground(new Color(239, 98, 215));
    VolverInicio.setForeground(new Color(239, 98, 215));
        
    }//GEN-LAST:event_VolverInicioMouseEntered

    private void VolverInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseExited
    VolverInicio.setBackground(Color.white);
    VolverInicio.setForeground(Color.white);
    }//GEN-LAST:event_VolverInicioMouseExited

    private void VolverInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseClicked
    new Visual.VentanaPrincipal().show(true);
    this.dispose();
    }//GEN-LAST:event_VolverInicioMouseClicked

    private void EntrarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarTXTMouseEntered
    BotonEntrar.setBackground(new Color(79, 90, 222));
    }//GEN-LAST:event_EntrarTXTMouseEntered

    private void EntrarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarTXTMouseExited
    BotonEntrar.setBackground(new Color(88,101,242));
    }//GEN-LAST:event_EntrarTXTMouseExited

    private void EntrarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarTXTMouseClicked
    String idUsuario = UsuarioField.getText().trim();
    if(idUsuario.isEmpty()){
        JOptionPane.showMessageDialog(this, "Por favor ingresa un ID de Usuario", "¡Ey no llenaste nada!", JOptionPane.WARNING_MESSAGE);
        }
    if(UsuarioField.getText().equals("Ingresa tu ID de usuario")){
        JOptionPane.showMessageDialog(this, "Por favor ingresa un ID de Usuario", "¡Ey no llenaste nada!", JOptionPane.WARNING_MESSAGE);
        }
    if(TSPrincipal.Sistema.iniciarSesion(Integer.parseInt(idUsuario))){
        JOptionPane.showMessageDialog(this, "Bienvenido al Sistema >w<", "¡Inicio de Sesión Exitoso!", JOptionPane.INFORMATION_MESSAGE);
        Usuario usuarioActual = TSPrincipal.Sistema.getUsuarioActual();
        usuarioActual.getCalendario().limpiarTareas();
        usuarioActual.cargarTareasDesdeArchivo();
    new Visual.VentanaMenuPrincipal().show(true);
    this.dispose();
    } else{
        JOptionPane.showMessageDialog(this, "Uh oh! no encontramos tu Usuario", "Usuario Errado o no Registrado", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_EntrarTXTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimeGirl;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonEntrar;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JLabel EligeOpcion;
    private javax.swing.JLabel EntrarTXT;
    private javax.swing.JLabel IconoTimeSaver;
    private javax.swing.JPanel Panel2Inicio;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel TedamoslaBienvenida;
    private javax.swing.JLabel TimeSaver;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JLabel UsuarioTXT;
    private javax.swing.JLabel VolverInicio;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
