/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import TSPrincipal.Tarea;
import TSPrincipal.Usuario;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;


public class VentanaEmergente1 extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEmergente1.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaEmergente1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorBG = new javax.swing.JPanel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NombreTXT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        DescripcionTXT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FechaTXT = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        AgregarBTN = new javax.swing.JPanel();
        AgregarTXT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrioridadTXT = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(147, 100, 160));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraSuperior.setBackground(new java.awt.Color(147, 100, 160));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(147, 100, 160));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 493, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 30));

        PanelMenu.setBackground(new java.awt.Color(203, 170, 224));
        PanelMenu.setForeground(new java.awt.Color(203, 170, 224));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresa el nombre de tu tarea:");

        NombreTXT.setBackground(new java.awt.Color(203, 170, 224));
        NombreTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        NombreTXT.setForeground(new java.awt.Color(0, 0, 0));
        NombreTXT.setText("Nombre");
        NombreTXT.setBorder(null);
        NombreTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreTXTMousePressed(evt);
            }
        });
        NombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTXTActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(30, 30, 30));

        DescripcionTXT.setBackground(new java.awt.Color(203, 170, 224));
        DescripcionTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        DescripcionTXT.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionTXT.setText("Descripción");
        DescripcionTXT.setBorder(null);
        DescripcionTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescripcionTXTMousePressed(evt);
            }
        });
        DescripcionTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionTXTActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(30, 30, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripción de tu tarea:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha limite de tu tarea (dd/mm/aaaa):");

        FechaTXT.setBackground(new java.awt.Color(203, 170, 224));
        FechaTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        FechaTXT.setForeground(new java.awt.Color(0, 0, 0));
        FechaTXT.setText("Fecha");
        FechaTXT.setBorder(null);
        FechaTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FechaTXTMousePressed(evt);
            }
        });
        FechaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaTXTActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(30, 30, 30));

        AgregarBTN.setBackground(new java.awt.Color(147, 100, 160));

        AgregarTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        AgregarTXT.setForeground(new java.awt.Color(0, 0, 0));
        AgregarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgregarTXT.setText("Agregar");
        AgregarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AgregarBTNLayout = new javax.swing.GroupLayout(AgregarBTN);
        AgregarBTN.setLayout(AgregarBTNLayout);
        AgregarBTNLayout.setHorizontalGroup(
            AgregarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        AgregarBTNLayout.setVerticalGroup(
            AgregarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgregarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prioridad:");

        PrioridadTXT.setBackground(new java.awt.Color(203, 170, 224));
        PrioridadTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        PrioridadTXT.setForeground(new java.awt.Color(0, 0, 0));
        PrioridadTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PrioridadTXT.setText("(1 - 5)");
        PrioridadTXT.setBorder(null);
        PrioridadTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrioridadTXTMousePressed(evt);
            }
        });
        PrioridadTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrioridadTXTActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(FechaTXT)
                        .addGap(62, 62, 62))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(NombreTXT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DescripcionTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addComponent(AgregarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5)
                                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelMenuLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelMenuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PrioridadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescripcionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(AgregarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(PrioridadTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        ColorBG.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 490, 270));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Tarea");
        ColorBG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 300, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    this.hide();
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void NombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTXTActionPerformed

    private void DescripcionTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionTXTActionPerformed

    private void FechaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaTXTActionPerformed

    private void AgregarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseExited
    AgregarBTN.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_AgregarTXTMouseExited

    private void AgregarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseEntered
    AgregarBTN.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_AgregarTXTMouseEntered

    private void AgregarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTXTMouseClicked
    Usuario usuarioactual = TSPrincipal.Sistema.getUsuarioActual();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    String Nombre = NombreTXT.getText().trim();
    String Descripcion = DescripcionTXT.getText().trim();
    String Fecha = FechaTXT.getText().trim();
    int Prioridad;
    Date fechalimite = null;
    int id = (int) (System.currentTimeMillis() % 10000);
    
    if(Integer.parseInt(PrioridadTXT.getText().trim())>=1 && Integer.parseInt(PrioridadTXT.getText().trim())<=5){
        Prioridad = Integer.parseInt(PrioridadTXT.getText().trim());
    } else {
        Prioridad = 1;
    }
    if(Nombre.isEmpty()||Descripcion.isEmpty()||Fecha.isEmpty()||Nombre.equals("Nombre")||Descripcion.equals("Descripción")||Fecha.equals("Fecha")){
        JOptionPane.showMessageDialog(this, "Por favor llena todos los espacios", "¡Ey no llenaste nada!", JOptionPane.WARNING_MESSAGE);
        } else{
        try{
        fechalimite = dateFormat.parse(Fecha);  
        }catch(Exception e){
        fechalimite = new Date();
    }
    Tarea nuevatarea = new Tarea(id,Nombre,Descripcion,fechalimite,Prioridad);
    usuarioactual.agregarTarea(nuevatarea);
    JOptionPane.showMessageDialog(this, nuevatarea);
    JOptionPane.showMessageDialog(this, "¡Añadiste una nueva tarea!", "¡Exito al agregar tarea!", JOptionPane.INFORMATION_MESSAGE);
    }
    usuarioactual.guardarTareasEnArchivo();
    
    
    }//GEN-LAST:event_AgregarTXTMouseClicked

    private void NombreTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTXTMousePressed
    NombreTXT.setText("");
    }//GEN-LAST:event_NombreTXTMousePressed

    private void DescripcionTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionTXTMousePressed
    DescripcionTXT.setText("");
    }//GEN-LAST:event_DescripcionTXTMousePressed

    private void FechaTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaTXTMousePressed
    FechaTXT.setText("");
    }//GEN-LAST:event_FechaTXTMousePressed

    private void PrioridadTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrioridadTXTMousePressed
    PrioridadTXT.setText("");
    }//GEN-LAST:event_PrioridadTXTMousePressed

    private void PrioridadTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrioridadTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrioridadTXTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarBTN;
    private javax.swing.JLabel AgregarTXT;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JTextField DescripcionTXT;
    private javax.swing.JTextField FechaTXT;
    private javax.swing.JTextField NombreTXT;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JTextField PrioridadTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
