/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        ColorBG = new javax.swing.JPanel();
        Panel2Inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IconoTimeSaver = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TedamoslaBienvenida = new javax.swing.JLabel();
        EligeOpcion = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JPanel();
        IniciarSesionTXT = new javax.swing.JLabel();
        Registrarse = new javax.swing.JPanel();
        RegistrarseTXT = new javax.swing.JLabel();
        Salir = new javax.swing.JPanel();
        SalirTXT = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(73, 38, 97));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2Inicio.setBackground(new java.awt.Color(147, 100, 160));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TimeSaver");

        IconoTimeSaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono.png"))); // NOI18N
        IconoTimeSaver.setToolTipText("");

        PanelMenu.setBackground(new java.awt.Color(46, 46, 52));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AnimeGirl.png"))); // NOI18N

        TedamoslaBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        TedamoslaBienvenida.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        TedamoslaBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        TedamoslaBienvenida.setText("¡Te damos la bienvenida de vuelta!");

        EligeOpcion.setBackground(new java.awt.Color(255, 255, 255));
        EligeOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EligeOpcion.setForeground(new java.awt.Color(255, 255, 255));
        EligeOpcion.setText("Elige una de las opciones a continuación:");

        IniciarSesion.setBackground(new java.awt.Color(39, 37, 37));

        IniciarSesionTXT.setBackground(new java.awt.Color(255, 255, 255));
        IniciarSesionTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        IniciarSesionTXT.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesionTXT.setText("Iniciar Sesión");
        IniciarSesionTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesionTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesionTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesionTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IniciarSesionLayout = new javax.swing.GroupLayout(IniciarSesion);
        IniciarSesion.setLayout(IniciarSesionLayout);
        IniciarSesionLayout.setHorizontalGroup(
            IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IniciarSesionTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IniciarSesionLayout.setVerticalGroup(
            IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IniciarSesionTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        Registrarse.setBackground(new java.awt.Color(39, 37, 37));

        RegistrarseTXT.setBackground(new java.awt.Color(255, 255, 255));
        RegistrarseTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        RegistrarseTXT.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarseTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrarseTXT.setText("Registrarse");
        RegistrarseTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarseTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarseTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarseTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistrarseLayout = new javax.swing.GroupLayout(Registrarse);
        Registrarse.setLayout(RegistrarseLayout);
        RegistrarseLayout.setHorizontalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
            .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistrarseTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        RegistrarseLayout.setVerticalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistrarseTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        Salir.setBackground(new java.awt.Color(39, 37, 37));

        SalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        SalirTXT.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        SalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        SalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalirTXT.setText("Salir");
        SalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SalirLayout = new javax.swing.GroupLayout(Salir);
        Salir.setLayout(SalirLayout);
        SalirLayout.setHorizontalGroup(
            SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SalirTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        SalirLayout.setVerticalGroup(
            SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SalirTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EligeOpcion)
                .addGap(137, 137, 137))
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(TedamoslaBienvenida)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40))))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TedamoslaBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EligeOpcion)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );

        javax.swing.GroupLayout Panel2InicioLayout = new javax.swing.GroupLayout(Panel2Inicio);
        Panel2Inicio.setLayout(Panel2InicioLayout);
        Panel2InicioLayout.setHorizontalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(IconoTimeSaver)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        Panel2InicioLayout.setVerticalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoTimeSaver))
                    .addGroup(Panel2InicioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        ColorBG.add(Panel2Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 410));

        BarraSuperior.setBackground(new java.awt.Color(73, 38, 97));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(73, 38, 97));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 750, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionTXTMouseEntered
    IniciarSesion.setBackground(new Color(42, 42, 48));
    }//GEN-LAST:event_IniciarSesionTXTMouseEntered

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    System.exit(0);
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void IniciarSesionTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionTXTMouseExited
    IniciarSesion.setBackground(new Color(39,37,37));
    }//GEN-LAST:event_IniciarSesionTXTMouseExited

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void RegistrarseTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseTXTMouseEntered
    Registrarse.setBackground(new Color(42, 42, 48));
    }//GEN-LAST:event_RegistrarseTXTMouseEntered

    private void RegistrarseTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseTXTMouseExited
    Registrarse.setBackground(new Color(39,37,37));
    }//GEN-LAST:event_RegistrarseTXTMouseExited

    private void SalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirTXTMouseEntered
    Salir.setBackground(new Color(42, 42, 48));
    }//GEN-LAST:event_SalirTXTMouseEntered

    private void SalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirTXTMouseExited
    Salir.setBackground(new Color(39,37,37));
    }//GEN-LAST:event_SalirTXTMouseExited

    private void SalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirTXTMouseClicked
    JOptionPane.showMessageDialog(this, "Muchas gracias por utilizar TimeSaver\n ¡Hasta la proxima!", "¡Adios (>w<)!", JOptionPane.INFORMATION_MESSAGE);
    System.exit(0);
    }//GEN-LAST:event_SalirTXTMouseClicked

    private void IniciarSesionTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionTXTMouseClicked
    new Visual.VentanaInicioSesion().setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_IniciarSesionTXTMouseClicked

    private void RegistrarseTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseTXTMouseClicked
    new Visual.VentanaRegistro().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_RegistrarseTXTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JLabel EligeOpcion;
    private javax.swing.JLabel IconoTimeSaver;
    private javax.swing.JPanel IniciarSesion;
    private javax.swing.JLabel IniciarSesionTXT;
    private javax.swing.JPanel Panel2Inicio;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel Registrarse;
    private javax.swing.JLabel RegistrarseTXT;
    private javax.swing.JPanel Salir;
    private javax.swing.JLabel SalirTXT;
    private javax.swing.JLabel TedamoslaBienvenida;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
