/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import TSPrincipal.Tarea;
import TSPrincipal.Usuario;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;


public class VentanaEmergente3 extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEmergente3.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaEmergente3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorBG = new javax.swing.JPanel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Complete = new javax.swing.JPanel();
        Editar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDTarea = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(147, 100, 160));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraSuperior.setBackground(new java.awt.Color(147, 100, 160));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(147, 100, 160));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalirTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        PanelMenu.setBackground(new java.awt.Color(203, 170, 224));
        PanelMenu.setForeground(new java.awt.Color(203, 170, 224));

        Complete.setBackground(new java.awt.Color(147, 100, 160));

        Editar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Editar.setForeground(new java.awt.Color(0, 0, 0));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("¡Completado!");
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CompleteLayout = new javax.swing.GroupLayout(Complete);
        Complete.setLayout(CompleteLayout);
        CompleteLayout.setHorizontalGroup(
            CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        CompleteLayout.setVerticalGroup(
            CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ingresa el ID de la tarea completada:");

        IDTarea.setBackground(new java.awt.Color(203, 170, 224));
        IDTarea.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        IDTarea.setForeground(new java.awt.Color(0, 0, 0));
        IDTarea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDTarea.setText("ID - Tarea");
        IDTarea.setBorder(null);
        IDTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDTareaMousePressed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Complete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(IDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Complete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        ColorBG.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 200));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tareas Completadas");
        ColorBG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    this.dispose();
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void IDTareaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTareaMousePressed
        IDTarea.setText("");
    }//GEN-LAST:event_IDTareaMousePressed

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Complete.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_EditarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Complete.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        Usuario usuarioactual = TSPrincipal.Sistema.getUsuarioActual();
         int Id_Tarea = Integer.parseInt(IDTarea.getText().trim());
         Tarea tarea = usuarioactual.getCalendario().buscarTareaPorId(Id_Tarea);
        if (tarea != null) {
            tarea.marcarComoCompletada();
            usuarioactual.guardarTareasEnArchivo();
            JOptionPane.showMessageDialog(this, "YEII! Completaste una tarea", "¡Felicitaciones! (>w<)", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uh oh! no encontre ninguna tarea con el ID: " + Id_Tarea, "Error encontrando Tarea", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JPanel Complete;
    private javax.swing.JLabel Editar;
    private javax.swing.JTextField IDTarea;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
