/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.*;


public class VentanaPomodoro extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPomodoro.class.getName());
    
    private Timer temporizador;
    private int Mili = 0;
    private int Min = 25;
    private int Sec = 60;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPomodoro() {
        initComponents();
        this.setLocationRelativeTo(null);
        temporizador = new Timer(10, (ActionEvent e) -> {
            IniciarCronometro();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorBG = new javax.swing.JPanel();
        Panel2Inicio = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        AnimeGirl = new javax.swing.JLabel();
        TimeSaver = new javax.swing.JLabel();
        IconoTimeSaver = new javax.swing.JLabel();
        Temporizador = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        IniciarBTN = new javax.swing.JPanel();
        IniciarTXT = new javax.swing.JLabel();
        PararBTN = new javax.swing.JPanel();
        PararTXT = new javax.swing.JLabel();
        ReiniciarBTN = new javax.swing.JPanel();
        ReiniciarTXT = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();
        VolverInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(73, 38, 97));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2Inicio.setBackground(new java.awt.Color(147, 100, 160));

        PanelMenu.setBackground(new java.awt.Color(203, 170, 224));

        AnimeGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AnimeGirl2.png"))); // NOI18N
        AnimeGirl.setToolTipText("");

        TimeSaver.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeSaver.setForeground(new java.awt.Color(0, 0, 0));
        TimeSaver.setText("TimeSaver");

        IconoTimeSaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono.png"))); // NOI18N
        IconoTimeSaver.setToolTipText("");

        Temporizador.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Temporizador.setForeground(new java.awt.Color(30, 30, 30));
        Temporizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temporizador.setText("TEMPORIZADOR POMODORO");
        Temporizador.setToolTipText("");

        Tiempo.setBackground(new java.awt.Color(226, 226, 226));
        Tiempo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 34)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(226, 226, 226));
        Tiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempo.setText("25m : 60s");

        IniciarBTN.setBackground(new java.awt.Color(189, 105, 189));

        IniciarTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        IniciarTXT.setForeground(new java.awt.Color(255, 255, 255));
        IniciarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarTXT.setText("INICIAR");
        IniciarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IniciarBTNLayout = new javax.swing.GroupLayout(IniciarBTN);
        IniciarBTN.setLayout(IniciarBTNLayout);
        IniciarBTNLayout.setHorizontalGroup(
            IniciarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IniciarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        IniciarBTNLayout.setVerticalGroup(
            IniciarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IniciarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        PararBTN.setBackground(new java.awt.Color(147, 100, 160));

        PararTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        PararTXT.setForeground(new java.awt.Color(255, 255, 255));
        PararTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PararTXT.setText("PARAR");
        PararTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PararTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PararTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PararTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PararTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PararBTNLayout = new javax.swing.GroupLayout(PararBTN);
        PararBTN.setLayout(PararBTNLayout);
        PararBTNLayout.setHorizontalGroup(
            PararBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PararTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        PararBTNLayout.setVerticalGroup(
            PararBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PararTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        ReiniciarBTN.setBackground(new java.awt.Color(147, 100, 160));

        ReiniciarTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ReiniciarTXT.setForeground(new java.awt.Color(255, 255, 255));
        ReiniciarTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReiniciarTXT.setText("REINICIAR");
        ReiniciarTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReiniciarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReiniciarTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReiniciarTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReiniciarTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ReiniciarBTNLayout = new javax.swing.GroupLayout(ReiniciarBTN);
        ReiniciarBTN.setLayout(ReiniciarBTNLayout);
        ReiniciarBTNLayout.setHorizontalGroup(
            ReiniciarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReiniciarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        ReiniciarBTNLayout.setVerticalGroup(
            ReiniciarBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReiniciarTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnimeGirl))
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(IniciarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(PararBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ReiniciarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoTimeSaver)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TimeSaver))
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(Temporizador))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IconoTimeSaver))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TimeSaver)
                        .addGap(18, 18, 18)
                        .addComponent(Temporizador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Tiempo)
                .addGap(19, 19, 19)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnimeGirl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PararBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReiniciarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IniciarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))))
        );

        javax.swing.GroupLayout Panel2InicioLayout = new javax.swing.GroupLayout(Panel2Inicio);
        Panel2Inicio.setLayout(Panel2InicioLayout);
        Panel2InicioLayout.setHorizontalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Panel2InicioLayout.setVerticalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        ColorBG.add(Panel2Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 410));

        BarraSuperior.setBackground(new java.awt.Color(73, 38, 97));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(73, 38, 97));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 750, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        VolverInicio.setBackground(new java.awt.Color(255, 255, 255));
        VolverInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        VolverInicio.setText("<- Volver al menu principal (> w <)");
        VolverInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverInicioMouseExited(evt);
            }
        });
        ColorBG.add(VolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarCronometro(){
        ActualizarTiempo();
        ActualizarLabel();
    }
    
    private void ActualizarTiempo(){
        Mili++;
        
        if(Mili == 60){
            Mili = 0;
            Sec--;
        }
        
        if(Sec == 00){
            Sec = 60;
            Min--;
        }
        
        if(Min == 00){
        temporizador.stop();
        IniciarTXT.setEnabled(true);
        JOptionPane.showMessageDialog(this, "¡Pomodoro Finalizado, tomate 5 minutos de descanso! (>w<)", "Pomodoro Finalizado", JOptionPane.INFORMATION_MESSAGE);
        Min = 25;
        Sec = 60;
        ActualizarLabel();
        }
        
    }
    
    private void ActualizarLabel(){
        String TempTXT = Min + "M" + " : " + Sec + "S";
        Tiempo.setText(TempTXT);
    }
    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    System.exit(0);
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void VolverInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseEntered
    VolverInicio.setBackground(new Color(239, 98, 215));
    VolverInicio.setForeground(new Color(239, 98, 215));
        
    }//GEN-LAST:event_VolverInicioMouseEntered

    private void VolverInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseExited
    VolverInicio.setBackground(Color.white);
    VolverInicio.setForeground(Color.white);
    }//GEN-LAST:event_VolverInicioMouseExited

    private void VolverInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseClicked
    new Visual.VentanaMenuPrincipal().show(true);
    this.dispose();
    }//GEN-LAST:event_VolverInicioMouseClicked

    private void IniciarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarTXTMouseEntered
    IniciarBTN.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_IniciarTXTMouseEntered

    private void PararTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PararTXTMouseEntered
    PararBTN.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_PararTXTMouseEntered

    private void ReiniciarTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarTXTMouseEntered
    ReiniciarBTN.setBackground(new Color(171, 125, 201));
    }//GEN-LAST:event_ReiniciarTXTMouseEntered

    private void IniciarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarTXTMouseExited
    IniciarBTN.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_IniciarTXTMouseExited

    private void PararTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PararTXTMouseExited
    PararBTN.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_PararTXTMouseExited

    private void ReiniciarTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarTXTMouseExited
    ReiniciarBTN.setBackground(new Color(147,100,160));
    }//GEN-LAST:event_ReiniciarTXTMouseExited

    private void IniciarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarTXTMouseClicked
    temporizador.start();   
    IniciarTXT.setEnabled(false);
    }//GEN-LAST:event_IniciarTXTMouseClicked

    private void PararTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PararTXTMouseClicked
    temporizador.stop();
    IniciarTXT.setEnabled(true);
    }//GEN-LAST:event_PararTXTMouseClicked

    private void ReiniciarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReiniciarTXTMouseClicked
    if(temporizador.isRunning()){
        temporizador.stop();
        IniciarTXT.setEnabled(true);
    }
        Min = 25;
        Sec = 60;
    ActualizarLabel();
    }//GEN-LAST:event_ReiniciarTXTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimeGirl;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JLabel IconoTimeSaver;
    private javax.swing.JPanel IniciarBTN;
    private javax.swing.JLabel IniciarTXT;
    private javax.swing.JPanel Panel2Inicio;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PararBTN;
    private javax.swing.JLabel PararTXT;
    private javax.swing.JPanel ReiniciarBTN;
    private javax.swing.JLabel ReiniciarTXT;
    private javax.swing.JLabel Temporizador;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel TimeSaver;
    private javax.swing.JLabel VolverInicio;
    // End of variables declaration//GEN-END:variables
}
