/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;


public class VentanaMenuPrincipal extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    LocalTime currentTime = LocalTime.now();
    String Horas = Integer.toString(currentTime.getHour());
    String Minutos = Integer.toString(currentTime.getMinute());
    String Momento;
    public String Hora(){
        if (0<=currentTime.getHour() && currentTime.getHour()<=12){
            Momento = "A.M";
        } else{
            Momento = "P.M";
        }
        return (Horas +":" + Minutos + Momento);
    }
    public String Bienvenido(){
        return("¡Hola "+TSPrincipal.Sistema.getUsuarioActual().getNombre()+"!");
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorBG = new javax.swing.JPanel();
        Panel2Inicio = new javax.swing.JPanel();
        PanelLindo = new javax.swing.JPanel();
        IconoTimeSaver = new javax.swing.JLabel();
        TimeSaver = new javax.swing.JLabel();
        HolaUser = new javax.swing.JLabel();
        EligeOpcion = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        AnimeGirl = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        FlechaGestionar = new javax.swing.JLabel();
        FlechaUsarPomo = new javax.swing.JLabel();
        FlechaConfig = new javax.swing.JLabel();
        GestionarTareas = new javax.swing.JPanel();
        GestionarTareasTXT = new javax.swing.JLabel();
        UsarPomodoro = new javax.swing.JPanel();
        UsarPomodoroTXT = new javax.swing.JLabel();
        ConfigurarUsuario = new javax.swing.JPanel();
        ConfigUserTXT = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JPanel();
        BotonSalirTXT = new javax.swing.JLabel();
        VolverInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        ColorBG.setBackground(new java.awt.Color(73, 38, 97));
        ColorBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2Inicio.setBackground(new java.awt.Color(147, 100, 160));

        PanelLindo.setBackground(new java.awt.Color(203, 170, 224));

        IconoTimeSaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Icono.png"))); // NOI18N
        IconoTimeSaver.setToolTipText("");

        TimeSaver.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        TimeSaver.setForeground(new java.awt.Color(0, 0, 0));
        TimeSaver.setText("TimeSaver");

        HolaUser.setBackground(new java.awt.Color(0, 0, 0));
        HolaUser.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        HolaUser.setForeground(new java.awt.Color(0, 0, 0));
        HolaUser.setText(Bienvenido());

        EligeOpcion.setBackground(new java.awt.Color(0, 0, 0));
        EligeOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        EligeOpcion.setForeground(new java.awt.Color(0, 0, 0));
        EligeOpcion.setText("La hora local es: ");

        Hora.setBackground(new java.awt.Color(226, 226, 226));
        Hora.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 34)); // NOI18N
        Hora.setForeground(new java.awt.Color(226, 226, 226));
        Hora.setText(Hora());

        AnimeGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AnimeGirl2.png"))); // NOI18N
        AnimeGirl.setToolTipText("");

        javax.swing.GroupLayout PanelLindoLayout = new javax.swing.GroupLayout(PanelLindo);
        PanelLindo.setLayout(PanelLindoLayout);
        PanelLindoLayout.setHorizontalGroup(
            PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLindoLayout.createSequentialGroup()
                .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLindoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(IconoTimeSaver)
                                .addGap(18, 18, 18)
                                .addComponent(TimeSaver))
                            .addComponent(HolaUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLindoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(EligeOpcion))
                            .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AnimeGirl)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelLindoLayout.setVerticalGroup(
            PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLindoLayout.createSequentialGroup()
                .addGroup(PanelLindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(IconoTimeSaver))
                    .addGroup(PanelLindoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TimeSaver)))
                .addGap(18, 18, 18)
                .addComponent(HolaUser)
                .addGap(18, 18, 18)
                .addComponent(EligeOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnimeGirl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelMenu.setBackground(new java.awt.Color(203, 170, 224));

        GestionarTareas.setBackground(new java.awt.Color(147, 100, 160));

        GestionarTareasTXT.setBackground(new java.awt.Color(0, 0, 0));
        GestionarTareasTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        GestionarTareasTXT.setForeground(new java.awt.Color(0, 0, 0));
        GestionarTareasTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GestionarTareasTXT.setText("Gestionar Tareas");
        GestionarTareasTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionarTareasTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionarTareasTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionarTareasTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionarTareasTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GestionarTareasLayout = new javax.swing.GroupLayout(GestionarTareas);
        GestionarTareas.setLayout(GestionarTareasLayout);
        GestionarTareasLayout.setHorizontalGroup(
            GestionarTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionarTareasTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        GestionarTareasLayout.setVerticalGroup(
            GestionarTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GestionarTareasTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        UsarPomodoro.setBackground(new java.awt.Color(147, 100, 160));

        UsarPomodoroTXT.setBackground(new java.awt.Color(0, 0, 0));
        UsarPomodoroTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        UsarPomodoroTXT.setForeground(new java.awt.Color(0, 0, 0));
        UsarPomodoroTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsarPomodoroTXT.setText("Usar Pomodoro");
        UsarPomodoroTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UsarPomodoroTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsarPomodoroTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsarPomodoroTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsarPomodoroTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout UsarPomodoroLayout = new javax.swing.GroupLayout(UsarPomodoro);
        UsarPomodoro.setLayout(UsarPomodoroLayout);
        UsarPomodoroLayout.setHorizontalGroup(
            UsarPomodoroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsarPomodoroTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        UsarPomodoroLayout.setVerticalGroup(
            UsarPomodoroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsarPomodoroTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        ConfigurarUsuario.setBackground(new java.awt.Color(147, 100, 160));

        ConfigUserTXT.setBackground(new java.awt.Color(0, 0, 0));
        ConfigUserTXT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ConfigUserTXT.setForeground(new java.awt.Color(0, 0, 0));
        ConfigUserTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfigUserTXT.setText("Configurar Usuario");
        ConfigUserTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfigUserTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfigUserTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfigUserTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfigUserTXTMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ConfigurarUsuarioLayout = new javax.swing.GroupLayout(ConfigurarUsuario);
        ConfigurarUsuario.setLayout(ConfigurarUsuarioLayout);
        ConfigurarUsuarioLayout.setHorizontalGroup(
            ConfigurarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfigUserTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        ConfigurarUsuarioLayout.setVerticalGroup(
            ConfigurarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfigUserTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(GestionarTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlechaGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsarPomodoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfigurarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FlechaUsarPomo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlechaConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GestionarTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FlechaGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsarPomodoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlechaUsarPomo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlechaConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfigurarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel2InicioLayout = new javax.swing.GroupLayout(Panel2Inicio);
        Panel2Inicio.setLayout(Panel2InicioLayout);
        Panel2InicioLayout.setHorizontalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(PanelLindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        Panel2InicioLayout.setVerticalGroup(
            Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2InicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel2InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelLindo, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ColorBG.add(Panel2Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 410));

        BarraSuperior.setBackground(new java.awt.Color(73, 38, 97));
        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        BotonSalir.setBackground(new java.awt.Color(73, 38, 97));

        BotonSalirTXT.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BotonSalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonSalirTXT.setText("X");
        BotonSalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSalirTXTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BotonSalirLayout = new javax.swing.GroupLayout(BotonSalir);
        BotonSalir.setLayout(BotonSalirLayout);
        BotonSalirLayout.setHorizontalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BotonSalirLayout.setVerticalGroup(
            BotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalirTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraSuperiorLayout.createSequentialGroup()
                .addGap(0, 750, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ColorBG.add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 30));

        VolverInicio.setBackground(new java.awt.Color(255, 255, 255));
        VolverInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        VolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        VolverInicio.setText("<- Volver al menu principal (> w <)");
        VolverInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverInicioMouseExited(evt);
            }
        });
        ColorBG.add(VolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColorBG, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorBG, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMousePressed
    
    }//GEN-LAST:event_BotonSalirTXTMousePressed

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed
    xMouse = evt.getX(); yMouse = evt.getY();
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
    int x = evt.getXOnScreen(); int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void BotonSalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseClicked
    System.exit(0);
    }//GEN-LAST:event_BotonSalirTXTMouseClicked

    private void BotonSalirTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseEntered
    BotonSalirTXT.setBackground(Color.red);
    BotonSalirTXT.setForeground(Color.red);
    }//GEN-LAST:event_BotonSalirTXTMouseEntered

    private void BotonSalirTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirTXTMouseExited
    BotonSalirTXT.setBackground(Color.white);
    BotonSalirTXT.setForeground(Color.white);
    }//GEN-LAST:event_BotonSalirTXTMouseExited

    private void VolverInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseEntered
    VolverInicio.setBackground(new Color(239, 98, 215));
    VolverInicio.setForeground(new Color(239, 98, 215));
        
    }//GEN-LAST:event_VolverInicioMouseEntered

    private void VolverInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseExited
    VolverInicio.setBackground(Color.white);
    VolverInicio.setForeground(Color.white);
    }//GEN-LAST:event_VolverInicioMouseExited

    private void VolverInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverInicioMouseClicked
    new Visual.VentanaPrincipal().show(true);
    this.dispose();
    }//GEN-LAST:event_VolverInicioMouseClicked

    private void GestionarTareasTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarTareasTXTMouseEntered
    GestionarTareas.setBackground(new Color(171, 125, 201)); 
    FlechaGestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flecha.png")));
    }//GEN-LAST:event_GestionarTareasTXTMouseEntered

    private void UsarPomodoroTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsarPomodoroTXTMouseEntered
    UsarPomodoro.setBackground(new Color(171, 125, 201));
    FlechaUsarPomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flecha.png")));
    }//GEN-LAST:event_UsarPomodoroTXTMouseEntered

    private void ConfigUserTXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigUserTXTMouseEntered
    ConfigurarUsuario.setBackground(new Color(171, 125, 201));  
    FlechaConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Flecha.png")));
    }//GEN-LAST:event_ConfigUserTXTMouseEntered

    private void GestionarTareasTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarTareasTXTMouseExited
    GestionarTareas.setBackground(new Color(147,100,160));
    FlechaGestionar.setIcon(null);
    }//GEN-LAST:event_GestionarTareasTXTMouseExited

    private void UsarPomodoroTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsarPomodoroTXTMouseExited
    UsarPomodoro.setBackground(new Color(147,100,160));
    FlechaUsarPomo.setIcon(null);
    }//GEN-LAST:event_UsarPomodoroTXTMouseExited

    private void ConfigUserTXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigUserTXTMouseExited
    ConfigurarUsuario.setBackground(new Color(147,100,160));
    FlechaConfig.setIcon(null);
    }//GEN-LAST:event_ConfigUserTXTMouseExited

    private void GestionarTareasTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarTareasTXTMouseClicked
    new Visual.VentanaGestionarTareas().show(true);
    this.dispose();
    }//GEN-LAST:event_GestionarTareasTXTMouseClicked

    private void UsarPomodoroTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsarPomodoroTXTMouseClicked
    new Visual.VentanaPomodoro().show(true);
    this.dispose();
    }//GEN-LAST:event_UsarPomodoroTXTMouseClicked

    private void ConfigUserTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfigUserTXTMouseClicked
    new Visual.VentanaConfigurarUsuario().show(true);
    }//GEN-LAST:event_ConfigUserTXTMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimeGirl;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JPanel BotonSalir;
    private javax.swing.JLabel BotonSalirTXT;
    private javax.swing.JPanel ColorBG;
    private javax.swing.JLabel ConfigUserTXT;
    private javax.swing.JPanel ConfigurarUsuario;
    private javax.swing.JLabel EligeOpcion;
    private javax.swing.JLabel FlechaConfig;
    private javax.swing.JLabel FlechaGestionar;
    private javax.swing.JLabel FlechaUsarPomo;
    private javax.swing.JPanel GestionarTareas;
    private javax.swing.JLabel GestionarTareasTXT;
    private javax.swing.JLabel HolaUser;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel IconoTimeSaver;
    private javax.swing.JPanel Panel2Inicio;
    private javax.swing.JPanel PanelLindo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel TimeSaver;
    private javax.swing.JPanel UsarPomodoro;
    private javax.swing.JLabel UsarPomodoroTXT;
    private javax.swing.JLabel VolverInicio;
    // End of variables declaration//GEN-END:variables
}
